version: '3.8'

services:
  # MongoDB
  mongodb:
    image: mongo:6
    container_name: notification-price-bot-mongodb
    restart: always
    volumes:
      - mongodb_data:/data/db
    ports:
      - '27017:27017'
    networks:
      - bot-network

  # Ứng dụng Bot
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: notification-price-bot
    restart: always
    depends_on:
      - mongodb
    env_file:
      - .env
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge

volumes:
  mongodb_data:
