version: '3.8'

services:
  # Ứng dụng Bot
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: notification-price-bot
    restart: always
    env_file:
      - .env
    volumes:
      - app_logs:/app/logs

volumes:
  app_logs:
